### ISSUE TITLE
[BUG] Could not find package magento/project-community-edition with version 2.4.5-p12.

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/github-actions-magento2#194]
# :bug: Bug report

I tried using these actions and recieved:

```bash
Could not find package magento/project-community-edition with version 2.4.5-p12.
```

## Current Behavior
I tried using these actions to install new version of Magento.

## Expected Behavior
I expect to be able to install the latest versions of Magento.

## Minimal reproduction of the problem with instructions
Use any of the actions that install Magento.

**Comment by damienwebdev** [comment]
This will occur for anyone who's pinned to `graycoreio/github-actions-magento2@main`. The MageOS team hasn't published the newest versions of the MageOS mirror yet, so these packages will error if you attempt to install them.

However, for nearly all of the actions, there's a `magento_repository` and a `composer_auth` input that you can use to overcome this.

For example:


```yaml
    - uses: graycoreio/github-actions-magento2/installation-test@main
      with:
        composer_version: ${{ matrix.composer }}
        php_version: ${{ matrix.php }}
        magento_version: ${{ matrix.magento }}
        composer_auth: ${{ secrets.COMPOSER_AUTH }}
        magento_repository: https://repo.magento.com/
        package_name: vendor/package
        source_folder: $GITHUB_WORKSPACE
```
