### ISSUE TITLE
[FEAT] Magento Store Validation Workflow

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/github-actions-magento2#82]
# :bulb: Feature request

## Feature Name
Marketplace Parity

## The Desired Behavior
The Github Actions should expose the same features that are available on the marketplace (for an extension) to the Github Community.

I would like a workflow that does the following:

- [ ] Varnish Compatibility
- [ ] Cypress Tests from Elegentos
- [ ] MFTF Core Subset Tests
- [ ] MFTF Tests (for the extension)
- [ ] Unit Tests (for the extension)
- [ ] Integration Tests (for the extension)
- [ ] [Coding Standard](https://github.com/graycoreio/github-actions-magento2/tree/main/coding-standard)
- [ ] [Quality Health Checks from Run as Root](https://github.com/run-as-root/gitlab-pipeline-templates/blob/master/static/phpmetrics.yaml#L17)
- [ ] [Installability Test](https://github.com/graycoreio/github-actions-magento2/tree/main/installation-test)
- [ ] Performance Test
- [ ] `classmap-authoritative` compliance
- [ ] `di:compile` compliance

across the following constraints

- [ ] `MAGE_MODE` as `developer` and `production`
- [ ] [`supported-versions`](https://github.com/graycoreio/github-actions-magento2/tree/main/supported-version)

The API for usage of this workflow should look something like below and should be as simple as possible to use. We can always support more complex configuration, for the new dev looking to get started out of the box, this action needs to be a good first step.

Each of these individual features can be implemented as a individual feature that people can use to make their own workflows, as well. 

```yml
name: Integration Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  magecheck:
    uses: graycoreio/github-actions-magento2/.github/workflows/magecheck.yaml@main
    secrets:
      composer_auth: ${{ secrets.COMPOSER_AUTH }}
```

## Your Use Case
As a developer, I want to publish provably high-quality extensions onto Github.

## Prior Work
https://developer.adobe.com/commerce/marketplace/guides/sellers/technical-review-guidelines/#extension-validation-and-qa

cc: @vbuck @DavidLambauer @peterjaap @Vinai
